export const LOAD_MOVIE_SUCCESS = 'LOAD_MOVIE_SUCCESS'
export const LOAD_MOVIE_FAILURE = 'LOAD_MOVIE_FAILURE'

export const LOAD_RECOMMENDATIONS_SUCCESS = 'LOAD_RECOMMENDATIONS_SUCCESS'
export const LOAD_RECOMMENDATIONS_FAILURE = 'LOAD_RECOMMENDATIONS_FAILURE'